Repository 2024-likelion-sswu/JoinUp_FE, pull requests merged in 2025-01, with the labels that each got.

#3 Feat: 하단바, 상단바, 로그인, 회원가입 구현
  JoinUp_FE/fe/package-lock.json
  JoinUp_FE/fe/package.json
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Footer/footer.scss
  JoinUp_FE/fe/src/assets/scss/section/Header/header.scss
  JoinUp_FE/fe/src/assets/scss/section/Login/btn.scss
  JoinUp_FE/fe/src/assets/scss/section/Login/login.scss
  JoinUp_FE/fe/src/assets/scss/section/Login/signup.scss
  JoinUp_FE/fe/src/assets/scss/setting/_common.scss
  JoinUp_FE/fe/src/assets/scss/setting/_resets.scss
  JoinUp_FE/fe/src/assets/scss/setting/_utils.scss
  JoinUp_FE/fe/src/assets/scss/setting/_variables.scss
  JoinUp_FE/fe/src/assets/scss/styles.scss
  JoinUp_FE/fe/src/components/footer_section/Footer.jsx
  JoinUp_FE/fe/src/components/header_section/Header.jsx
  JoinUp_FE/fe/src/components/login_section/Button.jsx
  JoinUp_FE/fe/src/components/login_section/LoginInput.jsx
  JoinUp_FE/fe/src/components/login_section/Signup1.jsx
  JoinUp_FE/fe/src/components/login_section/Signup2.jsx
  JoinUp_FE/fe/src/components/login_section/Signup3.jsx
  JoinUp_FE/fe/src/index.js
  JoinUp_FE/fe/src/pages/Login/LoginPage.jsx
  JoinUp_FE/fe/src/pages/Login/SignupPage.jsx
Labels: enhancement, FE

#5 Fix: app.js 하단바 적용 오류 수정
  JoinUp_FE/fe/src/App.js
Labels: bug, FE

#7 Feat: 채팅방 구현, Fix: footer 스타일 조정, 채팅 firebase 연결 및 회원가입 이메일로 변경
  JoinUp_FE/fe/package-lock.json
  JoinUp_FE/fe/package.json
  JoinUp_FE/fe/src/assets/JS/Firebase.js
  JoinUp_FE/fe/src/assets/scss/section/Footer/footer.scss
  JoinUp_FE/fe/src/assets/scss/section/Taxi_chatting/chat.scss
  JoinUp_FE/fe/src/assets/scss/section/Taxi_chatting/list.scss
  JoinUp_FE/fe/src/assets/scss/section/Taxi_chatting/message.scss
  JoinUp_FE/fe/src/assets/scss/setting/_variables.scss
  JoinUp_FE/fe/src/assets/scss/styles.scss
  JoinUp_FE/fe/src/components/login_section/Signup2.jsx
  JoinUp_FE/fe/src/components/main_section/Taxi_chatting/Chat.jsx
  JoinUp_FE/fe/src/components/main_section/Taxi_chatting/ChatList.jsx
  JoinUp_FE/fe/src/components/main_section/Taxi_chatting/ChatMessage.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatListPage.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatPage.jsx
Labels: enhancement, FE

#8 Feat: 마이페이지, 수정페이지, 커뮤니티, 게시판, 글쓰기 정적 페이지 구현 완료
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/images/BackBtn.svg
  JoinUp_FE/fe/src/assets/images/Camera.svg
  JoinUp_FE/fe/src/assets/images/Checking.svg
  JoinUp_FE/fe/src/assets/images/CommentBtn.svg
  JoinUp_FE/fe/src/assets/images/CouponBox.svg
  JoinUp_FE/fe/src/assets/images/FullHt.svg
  JoinUp_FE/fe/src/assets/images/GroupImg.svg
  JoinUp_FE/fe/src/assets/images/Ht.svg
  JoinUp_FE/fe/src/assets/images/Icon.svg
  JoinUp_FE/fe/src/assets/images/PayImg.svg
  JoinUp_FE/fe/src/assets/images/Pensil.svg
  JoinUp_FE/fe/src/assets/images/UserIcon.png
  JoinUp_FE/fe/src/assets/images/test.txt
  JoinUp_FE/fe/src/assets/scss/section/Community/community.scss
  JoinUp_FE/fe/src/assets/scss/section/MyPage/myedit.scss
  JoinUp_FE/fe/src/assets/scss/section/MyPage/mypage.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/addpost.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/post.scss
  JoinUp_FE/fe/src/components/Community_section/Community_Hot.jsx
  JoinUp_FE/fe/src/components/Community_section/Community_Notice.jsx
  JoinUp_FE/fe/src/components/Community_section/Community_Post.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Account.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Pay.jsx
  JoinUp_FE/fe/src/components/Post_section/HotPost.jsx
  JoinUp_FE/fe/src/components/Post_section/PostList.jsx
  JoinUp_FE/fe/src/pages/Community/Community.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyEdit.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyPage.jsx
  JoinUp_FE/fe/src/pages/Posting/AddPost.jsx
  JoinUp_FE/fe/src/pages/Posting/Post.jsx
Labels: enhancement, FE

#11 Fix: git merge 충돌 후 페이지 오류 해결
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/pages/Mypage/Coupon.jsx
  JoinUp_FE/fe/src/pages/Mypage/List.jsx
Labels: bug, FE

#14 Feat: 첫 랜딩 페이지 구현 완료, 파비콘 추가
  JoinUp_FE/fe/package-lock.json
  JoinUp_FE/fe/package.json
  JoinUp_FE/fe/public/favicon.ico
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/images/Logo/JoinUp_Full_Logo.png
  JoinUp_FE/fe/src/assets/images/Logo/JoinUp_Logo.png
  JoinUp_FE/fe/src/assets/scss/section/Landing/landing.scss
  JoinUp_FE/fe/src/assets/scss/styles.scss
  JoinUp_FE/fe/src/components/login_section/LoginInput.jsx
  JoinUp_FE/fe/src/components/login_section/Signup1.jsx
  JoinUp_FE/fe/src/components/login_section/Signup2.jsx
  JoinUp_FE/fe/src/components/login_section/Signup3.jsx
  JoinUp_FE/fe/src/pages/Landing/LandingPage.jsx
  JoinUp_FE/fe/src/pages/Login/LoginPage.jsx
  JoinUp_FE/fe/src/pages/Login/SignupPage.jsx
Labels: enhancement, FE

#17 Fix: 줄서기 홈 지도 스크롤 -> 클릭으로 변경
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Lineup/home_map.scss
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home_map.jsx
Labels: enhancement, FE

#18 Fix: footer style 조정
  JoinUp_FE/fe/src/assets/scss/section/Footer/footer.scss
Labels: enhancement, FE

#19 Feat: footer 페이지 별 링크 연결
  JoinUp_FE/fe/src/assets/scss/section/Footer/footer.scss
  JoinUp_FE/fe/src/assets/scss/section/Taxi_chatting/list.scss
  JoinUp_FE/fe/src/assets/scss/section/Taxi_chatting/message.scss
  JoinUp_FE/fe/src/components/footer_section/Footer.jsx
  JoinUp_FE/fe/src/components/login_section/Signup3.jsx
Labels: enhancement, FE

#20 Home, Home_map 백 연동
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Lineup/home.scss
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home_map.jsx
  JoinUp_FE/fe/src/pages/Lineup/Lineup_plus.jsx
Labels: enhancement, FE, API

#21 Home, map axios code fix
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home_map.jsx
Labels: enhancement, FE, API

#22 Feat: 채팅 api, 파이어베이스 연동 완료
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/components/main_section/Taxi_chatting/ChatList.jsx
  JoinUp_FE/fe/src/components/main_section/Taxi_chatting/ChatMessage.jsx
  JoinUp_FE/fe/src/pages/Login/LoginPage.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatListPage.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatPage.jsx
Labels: enhancement, FE, API

#23 Feat: 홈 줄서기에서 채팅하기 버튼 파이어베이스, api 연결 완료
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
Labels: enhancement, FE, API

#24 Feat: 하드코딩 .ver
  JoinUp_FE/fe/package-lock.json
  JoinUp_FE/fe/src/assets/images/Img10.png
  JoinUp_FE/fe/src/assets/images/Img9.png
  JoinUp_FE/fe/src/assets/images/Pencill.svg
  JoinUp_FE/fe/src/assets/images/SendBtn.svg
  JoinUp_FE/fe/src/assets/images/SendFullBtn.svg
  JoinUp_FE/fe/src/assets/scss/section/Community/community.scss
  JoinUp_FE/fe/src/assets/scss/section/MyPage/myedit.scss
  JoinUp_FE/fe/src/assets/scss/section/MyPage/mypage.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/Feed.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/addpost.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/post.scss
  JoinUp_FE/fe/src/components/Community_section/Community_Notice.jsx
  JoinUp_FE/fe/src/components/Community_section/Community_Post.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Account.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Pay.jsx
  JoinUp_FE/fe/src/components/Post_section/Feed.jsx
  JoinUp_FE/fe/src/components/Post_section/PostList.jsx
  JoinUp_FE/fe/src/pages/Community/Community.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyEdit.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyPage.jsx
  JoinUp_FE/fe/src/pages/Posting/AddPost.jsx
  JoinUp_FE/fe/src/pages/Posting/Post.jsx
Labels: enhancement, FE, API

#26 Feat: 커뮤니티 채팅 연결
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Community/community.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/post.scss
  JoinUp_FE/fe/src/components/Community_section/Community_Notice.jsx
  JoinUp_FE/fe/src/components/Community_section/Community_Post.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Account.jsx
  JoinUp_FE/fe/src/components/Post_section/PostList.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyPage.jsx
  JoinUp_FE/fe/src/pages/Posting/AddPost.jsx
  JoinUp_FE/fe/src/pages/Posting/Post.jsx
Labels: enhancement, FE, API

#27 fix home scss
  JoinUp_FE/fe/src/assets/images/지도 마커.png
  JoinUp_FE/fe/src/assets/scss/section/Lineup/home.scss
  JoinUp_FE/fe/src/assets/scss/section/Lineup/lineup_plus.scss
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home_map.jsx
  JoinUp_FE/fe/src/pages/Lineup/Lineup_plus.jsx
Labels: enhancement, FE

#28 Feat: 이슈 수정
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Community/community.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/Feed.scss
  JoinUp_FE/fe/src/assets/scss/section/Posting/post.scss
  JoinUp_FE/fe/src/components/Community_section/Community_Post.jsx
  JoinUp_FE/fe/src/components/Post_section/Feed.jsx
  JoinUp_FE/fe/src/components/Post_section/PostList.jsx
  JoinUp_FE/fe/src/components/login_section/Signup1.jsx
  JoinUp_FE/fe/src/pages/Community/Community.jsx
  JoinUp_FE/fe/src/pages/Mypage/Coupon.jsx
  JoinUp_FE/fe/src/pages/Mypage/List.jsx
Labels: enhancement, FE

#29 Fix: 코드 정리
  JoinUp_BE/test.txt
  JoinUp_FE/fe/src/App.js
  JoinUp_FE/fe/src/assets/scss/section/Community/community.scss
  JoinUp_FE/fe/src/components/Community_section/Community_Post.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Account.jsx
  JoinUp_FE/fe/src/components/MyPage_section/Pay.jsx
  JoinUp_FE/fe/src/components/Post_section/Feed.jsx
  JoinUp_FE/fe/src/components/login_section/Signup1.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home.jsx
  JoinUp_FE/fe/src/pages/Lineup/Home_map.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyEdit.jsx
  JoinUp_FE/fe/src/pages/MyPage/MyPage.jsx
  JoinUp_FE/fe/src/pages/Posting/Post.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatListPage.jsx
  JoinUp_FE/fe/src/pages/Taxi_chatting/LiveChatPage.jsx
Labels: enhancement, FE
